name: pytest

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  pytest:
    name: Run tests
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          repository: 'yedpodtrzitko/TagStudio'
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'

      - name: Install system dependencies
        run: |
          # dont run update, it is slow
          # sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
            libxkbcommon-x11-0 \
            x11-utils \
            libyaml-dev \
            libegl1 \
            libxcb-icccm4 \
            libxcb-image0 \
            libxcb-keysyms1 \
            libxcb-randr0 \
            libxcb-render-util0 \
            libxcb-xinerama0 \
            libopengl0 \
            libxcb-cursor0 \
            libpulse0

      - name: Install dependencies
        run: |
          python -m pip install --upgrade uv
          uv pip install --system -r requirements.txt
          uv pip install --system -r requirements-dev.txt

      - name: Run pytest
        run: >-
          xvfb-run pytest
          --cov-report xml:coverage.xml
          --cov=.
          --junitxml=testresults.xml
          tagstudio/tests

      - name: SonarQube Cloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v5
        with:
          report_paths: "${{ github.workspace }}/testresults.xml"
          check_name: 📈 Test results
          require_tests: true
          fail_on_failure: true
          annotations_limit: 200
